version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      cargo-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/apps/web"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    groups:
      docker-minor-patch:
        update-types:
          - "minor"
          - "patch"
