use std::{
    collections::HashMap,
    env, fs,
    net::{IpAddr, SocketAddr},
    path::{Path, PathBuf},
    sync::Arc,
    time::{Duration, Instant},
};

use argon2::{Argon2, PasswordHash, PasswordHasher, PasswordVerifier, password_hash::SaltString};
use axum::{
    Json,
    extract::{ConnectInfo, Request, State},
    http::{
        HeaderMap, HeaderValue, Method, StatusCode,
        header::{COOKIE, HOST, ORIGIN, SET_COOKIE, UPGRADE},
    },
    middleware::Next,
    response::{IntoResponse, Response},
};
use serde::{Deserialize, Serialize};
use tokio::sync::{Mutex, RwLock};
use totp_rs::{Algorithm, Secret, TOTP};
use tracing::warn;

use crate::{
    audit::AuditLog, error_response, fsutil::atomic_write_secure, request_context::RequestId,
};

const DEFAULT_PASSWORD_HASH_FILE: &str = "/var/lib/deckox/admin-password.hash";
const SESSION_COOKIE: &str = "deckox_session";
const PREAUTH_COOKIE: &str = "deckox_preauth";
const SESSION_TTL: Duration = Duration::from_secs(12 * 60 * 60);
const PREAUTH_TTL: Duration = Duration::from_secs(5 * 60);
const PENDING_TOTP_SETUP_TTL: Duration = Duration::from_secs(5 * 60);
const FAILURE_WINDOW: Duration = Duration::from_secs(5 * 60);
const MAX_FAILURES: u32 = 5;
const MAX_PASSWORD_BYTES: usize = 1024;
const MIN_PASSWORD_BYTES: usize = 12;
const TOTP_ISSUER: &str = "Deckox";
const TOTP_DIGITS: usize = 6;
const TOTP_SKEW: u8 = 1;
const TOTP_STEP: u64 = 30;
const RECOVERY_CODE_COUNT: usize = 10;

/// Key of the single administrator account in [`AccountFile`]. The file is
/// already keyed by username so Deckox can grow multiple accounts later
/// without another migration; today only this one key is ever populated.
pub const ADMIN_ACCOUNT: &str = "admin";

/// On-disk shape of the admin account file (JSON). Written atomically and
/// read back on every [`AuthManager::load`] and every CLI recovery command.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AccountFile {
    pub accounts: HashMap<String, Account>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Account {
    pub password_hash: String,
    #[serde(default)]
    pub totp: Option<TotpSecret>,
    #[serde(default)]
    pub updated_at_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TotpSecret {
    pub secret_base32: String,
    pub recovery_code_hashes: Vec<String>,
    /// The TOTP time-step last accepted for this account, if any. Codes
    /// matching this step or an older one are rejected so a captured code
    /// cannot be replayed for the rest of its ~90s (skew ±1) validity window.
    #[serde(default)]
    pub last_used_step: Option<u64>,
}

#[derive(Clone)]
pub struct AuthManager {
    inner: Arc<AuthInner>,
}

struct AuthInner {
    account: RwLock<Account>,
    account_path: Option<PathBuf>,
    secure_cookie: bool,
    sessions: Mutex<HashMap<String, Instant>>,
    failures: Mutex<HashMap<IpAddr, FailedLogins>>,
    password_change_failures: Mutex<HashMap<IpAddr, FailedLogins>>,
    totp_login_failures: Mutex<HashMap<IpAddr, FailedLogins>>,
    account_write: Mutex<()>,
    audit: AuditLog,
    /// Password verified, TOTP not yet: keyed by a short-lived pre-auth
    /// token handed to the browser instead of the real session cookie.
    pending_logins: Mutex<HashMap<String, Instant>>,
    /// A TOTP secret generated by `totp/setup` but not yet confirmed with a
    /// code, keyed by the session token of the admin who requested it.
    pending_totp_setup: Mutex<HashMap<String, PendingTotpSetup>>,
}

struct FailedLogins {
    count: u32,
    started_at: Instant,
}

#[derive(Clone)]
struct PendingTotpSetup {
    secret_base32: String,
    expires_at: Instant,
}

#[derive(Clone)]
pub struct AuthenticatedUser {
    pub source_ip: IpAddr,
}

#[derive(Deserialize)]
pub struct LoginRequest {
    password: String,
}

#[derive(Deserialize)]
pub struct ChangePasswordRequest {
    current_password: String,
    new_password: String,
}

#[derive(Deserialize)]
pub struct LoginTotpRequest {
    code: String,
}

#[derive(Deserialize)]
pub struct TotpConfirmRequest {
    code: String,
}

#[derive(Deserialize)]
pub struct TotpDisableRequest {
    current_password: String,
    code: String,
}

#[derive(Serialize)]
pub struct AuthStatus {
    authenticated: bool,
    totp_required: bool,
}

impl AuthStatus {
    const fn authenticated() -> Self {
        Self {
            authenticated: true,
            totp_required: false,
        }
    }

    const fn unauthenticated() -> Self {
        Self {
            authenticated: false,
            totp_required: false,
        }
    }

    const fn totp_required() -> Self {
        Self {
            authenticated: false,
            totp_required: true,
        }
    }
}

#[derive(Serialize)]
pub struct TotpStatusResponse {
    enabled: bool,
    recovery_codes_remaining: usize,
}

#[derive(Serialize)]
pub struct TotpSetupResponse {
    secret_base32: String,
    otpauth_uri: String,
}

#[derive(Serialize)]
pub struct TotpConfirmResponse {
    recovery_codes: Vec<String>,
}

enum LoginResult {
    Authenticated(String),
    TotpRequired(String),
    Invalid,
    RateLimited,
}

enum LoginTotpResult {
    Authenticated(String),
    Invalid,
    RateLimited,
    NoPendingLogin,
}

enum ChangePasswordResult {
    Changed,
    InvalidCurrentPassword,
    RateLimited,
    InvalidNewPassword,
    NotPersistent,
    Failed(String),
}

pub enum PasswordConfirmationResult {
    Confirmed,
    Invalid,
    RateLimited,
}

enum TotpSetupResult {
    Ready {
        secret_base32: String,
        otpauth_uri: String,
    },
    NotPersistent,
    Failed(String),
}

enum TotpConfirmResult {
    Confirmed(Vec<String>),
    InvalidCode,
    NoPendingSetup,
    NotPersistent,
    Failed(String),
}

enum TotpDisableResult {
    Disabled,
    NotEnabled,
    InvalidCurrentPassword,
    InvalidCode,
    RateLimited,
    NotPersistent,
    Failed(String),
}

impl AuthManager {
    pub fn load(audit: AuditLog) -> Result<Self, String> {
        let (account, account_path) = if let Ok(password_hash) =
            env::var("DECKOX_ADMIN_PASSWORD_HASH")
        {
            let password_hash = password_hash.trim().to_owned();
            PasswordHash::new(&password_hash)
                .map_err(|error| format!("invalid admin password hash: {error}"))?;
            (
                Account {
                    password_hash,
                    totp: None,
                    updated_at_ms: 0,
                },
                None,
            )
        } else {
            let path = PathBuf::from(
                env::var("DECKOX_ADMIN_PASSWORD_HASH_FILE")
                    .unwrap_or_else(|_| DEFAULT_PASSWORD_HASH_FILE.to_owned()),
            );
            let account_file = load_account_file(&path)
                .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
            let account = account_file
                .accounts
                .get(ADMIN_ACCOUNT)
                .cloned()
                .ok_or_else(|| format!("{} does not contain an admin account", path.display()))?;
            (account, Some(path))
        };

        let secure_cookie = env::var("DECKOX_SECURE_COOKIE").is_ok_and(|value| value == "true");
        Ok(Self {
            inner: Arc::new(AuthInner {
                account: RwLock::new(account),
                account_path,
                secure_cookie,
                sessions: Mutex::new(HashMap::new()),
                failures: Mutex::new(HashMap::new()),
                password_change_failures: Mutex::new(HashMap::new()),
                totp_login_failures: Mutex::new(HashMap::new()),
                account_write: Mutex::new(()),
                audit,
                pending_logins: Mutex::new(HashMap::new()),
                pending_totp_setup: Mutex::new(HashMap::new()),
            }),
        })
    }

    async fn login(&self, source_ip: IpAddr, password: String) -> LoginResult {
        if password.is_empty() || password.len() > MAX_PASSWORD_BYTES {
            record_failure(&self.inner.failures, source_ip).await;
            return LoginResult::Invalid;
        }
        if is_rate_limited(&self.inner.failures, source_ip).await {
            return LoginResult::RateLimited;
        }

        let account = self.inner.account.read().await.clone();
        let valid = verify_password(account.password_hash.clone(), password).await;

        if !valid {
            record_failure(&self.inner.failures, source_ip).await;
            return LoginResult::Invalid;
        }

        self.inner.failures.lock().await.remove(&source_ip);
        self.inner
            .password_change_failures
            .lock()
            .await
            .remove(&source_ip);

        if account.totp.is_some() {
            let preauth_token = hex::encode(rand::random::<[u8; 32]>());
            let now = Instant::now();
            let mut pending = self.inner.pending_logins.lock().await;
            pending.retain(|_, expires_at| *expires_at > now);
            pending.insert(preauth_token.clone(), now + PREAUTH_TTL);
            drop(pending);
            return LoginResult::TotpRequired(preauth_token);
        }

        let token = hex::encode(rand::random::<[u8; 32]>());
        self.inner
            .sessions
            .lock()
            .await
            .insert(token.clone(), Instant::now() + SESSION_TTL);
        LoginResult::Authenticated(token)
    }

    async fn login_totp(
        &self,
        source_ip: IpAddr,
        headers: &HeaderMap,
        code: String,
    ) -> LoginTotpResult {
        let Some(preauth_token) = preauth_token(headers) else {
            return LoginTotpResult::NoPendingLogin;
        };
        if is_rate_limited(&self.inner.totp_login_failures, source_ip).await {
            return LoginTotpResult::RateLimited;
        }

        let now = Instant::now();
        let mut pending = self.inner.pending_logins.lock().await;
        pending.retain(|_, expires_at| *expires_at > now);
        let is_pending = pending.remove(&preauth_token).is_some();
        drop(pending);
        if !is_pending {
            return LoginTotpResult::NoPendingLogin;
        }

        let mut account = self.inner.account.read().await.clone();
        let valid = verify_totp_or_recovery_code(&mut account, &code).await;
        if !valid {
            record_failure(&self.inner.totp_login_failures, source_ip).await;
            return LoginTotpResult::Invalid;
        }
        if let Some(account_path) = self.inner.account_path.clone() {
            // Best-effort: the submitted code was valid either way. If this
            // write fails, the consumed recovery code reverts to available
            // on the next process restart rather than blocking the login.
            if let Err(error) = write_account(&account_path, &account).await {
                warn!(%error, "failed to persist recovery code consumption");
            }
        }
        *self.inner.account.write().await = account;

        self.inner
            .totp_login_failures
            .lock()
            .await
            .remove(&source_ip);
        let token = hex::encode(rand::random::<[u8; 32]>());
        self.inner
            .sessions
            .lock()
            .await
            .insert(token.clone(), Instant::now() + SESSION_TTL);
        LoginTotpResult::Authenticated(token)
    }

    async fn change_password(
        &self,
        source_ip: IpAddr,
        current_password: String,
        new_password: String,
    ) -> ChangePasswordResult {
        let _change_guard = self.inner.account_write.lock().await;
        let Some(account_path) = self.inner.account_path.clone() else {
            return ChangePasswordResult::NotPersistent;
        };
        if validate_new_password(&new_password).is_err() {
            return ChangePasswordResult::InvalidNewPassword;
        }
        if is_rate_limited(&self.inner.password_change_failures, source_ip).await {
            return ChangePasswordResult::RateLimited;
        }

        let current_hash = self.inner.account.read().await.password_hash.clone();
        if !verify_password(current_hash, current_password).await {
            record_failure(&self.inner.password_change_failures, source_ip).await;
            return ChangePasswordResult::InvalidCurrentPassword;
        }
        self.inner
            .password_change_failures
            .lock()
            .await
            .remove(&source_ip);

        let password_to_hash = new_password;
        let new_hash =
            match tokio::task::spawn_blocking(move || hash_password(&password_to_hash)).await {
                Ok(Ok(hash)) => hash,
                Ok(Err(error)) => return ChangePasswordResult::Failed(error),
                Err(error) => {
                    return ChangePasswordResult::Failed(format!(
                        "password hashing task failed: {error}"
                    ));
                }
            };

        let mut account = self.inner.account.read().await.clone();
        account.password_hash = new_hash;
        account.updated_at_ms = now_ms();
        if let Err(error) = write_account(&account_path, &account).await {
            return ChangePasswordResult::Failed(error);
        }
        *self.inner.account.write().await = account;

        self.inner.sessions.lock().await.clear();
        self.inner.failures.lock().await.clear();
        ChangePasswordResult::Changed
    }

    pub async fn confirm_current_password(
        &self,
        source_ip: IpAddr,
        password: String,
    ) -> PasswordConfirmationResult {
        if password.is_empty() || password.len() > MAX_PASSWORD_BYTES {
            record_failure(&self.inner.password_change_failures, source_ip).await;
            return PasswordConfirmationResult::Invalid;
        }
        if is_rate_limited(&self.inner.password_change_failures, source_ip).await {
            return PasswordConfirmationResult::RateLimited;
        }

        let password_hash = self.inner.account.read().await.password_hash.clone();
        if !verify_password(password_hash, password).await {
            record_failure(&self.inner.password_change_failures, source_ip).await;
            return PasswordConfirmationResult::Invalid;
        }
        self.inner
            .password_change_failures
            .lock()
            .await
            .remove(&source_ip);
        PasswordConfirmationResult::Confirmed
    }

    async fn is_authenticated(&self, headers: &HeaderMap) -> bool {
        let Some(token) = session_token(headers) else {
            return false;
        };
        let now = Instant::now();
        let mut sessions = self.inner.sessions.lock().await;
        sessions.retain(|_, expires_at| *expires_at > now);
        sessions
            .get(&token)
            .is_some_and(|expires_at| *expires_at > now)
    }

    async fn logout(&self, headers: &HeaderMap) {
        if let Some(token) = session_token(headers) {
            self.inner.sessions.lock().await.remove(&token);
        }
    }

    async fn totp_status(&self) -> TotpStatusResponse {
        self.inner.account.read().await.totp.as_ref().map_or(
            TotpStatusResponse {
                enabled: false,
                recovery_codes_remaining: 0,
            },
            |totp| TotpStatusResponse {
                enabled: true,
                recovery_codes_remaining: totp.recovery_code_hashes.len(),
            },
        )
    }

    async fn totp_setup(&self, session_token: &str) -> TotpSetupResult {
        if self.inner.account_path.is_none() {
            return TotpSetupResult::NotPersistent;
        }
        let totp = match generate_totp_secret() {
            Ok(totp) => totp,
            Err(error) => return TotpSetupResult::Failed(error),
        };
        let secret_base32 = totp.get_secret_base32();
        let otpauth_uri = totp.get_url();

        let now = Instant::now();
        let mut pending = self.inner.pending_totp_setup.lock().await;
        pending.retain(|_, entry| entry.expires_at > now);
        pending.insert(
            session_token.to_owned(),
            PendingTotpSetup {
                secret_base32: secret_base32.clone(),
                expires_at: now + PENDING_TOTP_SETUP_TTL,
            },
        );
        drop(pending);
        TotpSetupResult::Ready {
            secret_base32,
            otpauth_uri,
        }
    }

    async fn totp_confirm(&self, session_token: &str, code: String) -> TotpConfirmResult {
        let Some(account_path) = self.inner.account_path.clone() else {
            return TotpConfirmResult::NotPersistent;
        };

        let now = Instant::now();
        let mut pending = self.inner.pending_totp_setup.lock().await;
        pending.retain(|_, entry| entry.expires_at > now);
        let Some(entry) = pending.get(session_token).cloned() else {
            return TotpConfirmResult::NoPendingSetup;
        };
        drop(pending);

        let totp = match build_totp(&entry.secret_base32) {
            Ok(totp) => totp,
            Err(error) => return TotpConfirmResult::Failed(error),
        };
        let Some(step) = totp_matching_step(&totp, &code, None) else {
            return TotpConfirmResult::InvalidCode;
        };

        let recovery_codes = generate_recovery_codes();
        let recovery_code_hashes = match hash_recovery_codes(&recovery_codes).await {
            Ok(hashes) => hashes,
            Err(error) => return TotpConfirmResult::Failed(error),
        };

        let mut account = self.inner.account.read().await.clone();
        account.totp = Some(TotpSecret {
            secret_base32: entry.secret_base32,
            recovery_code_hashes,
            last_used_step: Some(step),
        });
        account.updated_at_ms = now_ms();
        if let Err(error) = write_account(&account_path, &account).await {
            return TotpConfirmResult::Failed(error);
        }
        *self.inner.account.write().await = account;
        self.inner
            .pending_totp_setup
            .lock()
            .await
            .remove(session_token);

        TotpConfirmResult::Confirmed(recovery_codes)
    }

    async fn totp_disable(
        &self,
        source_ip: IpAddr,
        current_password: String,
        code: String,
    ) -> TotpDisableResult {
        let Some(account_path) = self.inner.account_path.clone() else {
            return TotpDisableResult::NotPersistent;
        };
        if is_rate_limited(&self.inner.password_change_failures, source_ip).await {
            return TotpDisableResult::RateLimited;
        }

        let mut account = self.inner.account.read().await.clone();
        if !verify_password(account.password_hash.clone(), current_password).await {
            record_failure(&self.inner.password_change_failures, source_ip).await;
            return TotpDisableResult::InvalidCurrentPassword;
        }
        if account.totp.is_none() {
            return TotpDisableResult::NotEnabled;
        }
        if !verify_totp_or_recovery_code(&mut account, &code).await {
            record_failure(&self.inner.password_change_failures, source_ip).await;
            return TotpDisableResult::InvalidCode;
        }
        self.inner
            .password_change_failures
            .lock()
            .await
            .remove(&source_ip);

        account.totp = None;
        account.updated_at_ms = now_ms();
        if let Err(error) = write_account(&account_path, &account).await {
            return TotpDisableResult::Failed(error);
        }
        *self.inner.account.write().await = account;
        TotpDisableResult::Disabled
    }

    fn session_cookie(&self, token: &str) -> String {
        self.cookie(SESSION_COOKIE, token, SESSION_TTL.as_secs())
    }

    fn expired_cookie(&self) -> String {
        self.expired(SESSION_COOKIE)
    }

    fn preauth_cookie(&self, token: &str) -> String {
        self.cookie(PREAUTH_COOKIE, token, PREAUTH_TTL.as_secs())
    }

    fn expired_preauth_cookie(&self) -> String {
        self.expired(PREAUTH_COOKIE)
    }

    fn cookie(&self, name: &str, token: &str, max_age_secs: u64) -> String {
        let secure = if self.inner.secure_cookie {
            "; Secure"
        } else {
            ""
        };
        format!("{name}={token}; Path=/; HttpOnly; SameSite=Strict; Max-Age={max_age_secs}{secure}")
    }

    fn expired(&self, name: &str) -> String {
        let secure = if self.inner.secure_cookie {
            "; Secure"
        } else {
            ""
        };
        format!("{name}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0{secure}")
    }

    pub fn audit(&self) -> &AuditLog {
        &self.inner.audit
    }
}

/// Builds a [`TOTP`] from a newly generated random secret, for the setup
/// step. `account_name` is fixed to [`ADMIN_ACCOUNT`] since Deckox has one
/// administrator today.
fn generate_totp_secret() -> Result<TOTP, String> {
    let secret_bytes = Secret::generate_secret()
        .to_bytes()
        .map_err(|error| format!("failed to generate TOTP secret: {error}"))?;
    build_totp_from_bytes(secret_bytes)
}

/// Rebuilds the [`TOTP`] used to verify codes against a previously stored,
/// base32-encoded secret.
fn build_totp(secret_base32: &str) -> Result<TOTP, String> {
    let secret_bytes = Secret::Encoded(secret_base32.to_owned())
        .to_bytes()
        .map_err(|error| format!("invalid TOTP secret: {error}"))?;
    build_totp_from_bytes(secret_bytes)
}

fn build_totp_from_bytes(secret_bytes: Vec<u8>) -> Result<TOTP, String> {
    TOTP::new(
        Algorithm::SHA1,
        TOTP_DIGITS,
        TOTP_SKEW,
        TOTP_STEP,
        secret_bytes,
        Some(TOTP_ISSUER.to_owned()),
        ADMIN_ACCOUNT.to_owned(),
    )
    .map_err(|error| format!("invalid TOTP configuration: {error}"))
}

/// Generates human-typeable one-time recovery codes (`XXXXX-XXXXX`, 40 bits
/// of entropy each). Callers hash these with [`hash_recovery_codes`] before
/// persisting — only the plaintext response to the confirming client ever
/// sees them.
fn generate_recovery_codes() -> Vec<String> {
    (0..RECOVERY_CODE_COUNT)
        .map(|_| {
            let raw = hex::encode(rand::random::<[u8; 5]>()).to_uppercase();
            format!("{}-{}", &raw[..5], &raw[5..])
        })
        .collect()
}

async fn hash_recovery_codes(codes: &[String]) -> Result<Vec<String>, String> {
    let codes = codes.to_vec();
    tokio::task::spawn_blocking(move || {
        codes
            .iter()
            .map(|code| hash_password(code))
            .collect::<Result<Vec<_>, _>>()
    })
    .await
    .map_err(|error| format!("recovery code hashing task failed: {error}"))?
}

/// Checks `code` against the account's TOTP secret first, then falls back to
/// the stored recovery codes. A matching recovery code is removed from
/// `account` (one-time use) — the caller is responsible for persisting that
/// change.
async fn verify_totp_or_recovery_code(account: &mut Account, code: &str) -> bool {
    let Some(totp_secret) = account.totp.clone() else {
        return false;
    };
    if let Ok(totp) = build_totp(&totp_secret.secret_base32)
        && let Some(step) = totp_matching_step(&totp, code, totp_secret.last_used_step)
    {
        if let Some(totp_mut) = account.totp.as_mut() {
            totp_mut.last_used_step = Some(step);
        }
        return true;
    }

    let Some(totp) = account.totp.as_mut() else {
        return false;
    };
    for index in 0..totp.recovery_code_hashes.len() {
        if verify_password(totp.recovery_code_hashes[index].clone(), code.to_owned()).await {
            totp.recovery_code_hashes.remove(index);
            return true;
        }
    }
    false
}

/// Returns the TOTP time-step `code` matches, if any, restricted to steps
/// strictly newer than `after_step`. Mirrors [`TOTP::check`]'s skew window
/// but additionally rejects a code already accepted for an equal-or-older
/// step, so a captured code cannot be replayed within its validity window.
fn totp_matching_step(totp: &TOTP, code: &str, after_step: Option<u64>) -> Option<u64> {
    let now_secs = now_ms() / 1000;
    let base_step = now_secs / TOTP_STEP;
    let skew = u64::from(TOTP_SKEW);
    (base_step.saturating_sub(skew)..=base_step + skew).find(|&step| {
        after_step.is_none_or(|after| step > after) && totp.generate(step * TOTP_STEP) == code
    })
}

/// Resolves the account file path a CLI recovery command should operate on.
/// Returns `None` when the server is configured for the non-persistent
/// `DECKOX_ADMIN_PASSWORD_HASH` mode, in which there is no file to edit.
pub fn account_path_from_env() -> Option<PathBuf> {
    if env::var("DECKOX_ADMIN_PASSWORD_HASH").is_ok() {
        return None;
    }
    Some(PathBuf::from(
        env::var("DECKOX_ADMIN_PASSWORD_HASH_FILE")
            .unwrap_or_else(|_| DEFAULT_PASSWORD_HASH_FILE.to_owned()),
    ))
}

/// Parses an account file, transparently upgrading the legacy format (a bare
/// Argon2id hash string, with no JSON structure) that every Deckox install
/// before this feature wrote. The upgraded form is only persisted the next
/// time the account is written (password change, TOTP enable/disable, or a
/// CLI recovery command) — reading never touches the file on disk.
pub fn load_account_file(path: &Path) -> Result<AccountFile, String> {
    let content = fs::read_to_string(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    let trimmed = content.trim();

    if let Ok(parsed) = serde_json::from_str::<AccountFile>(trimmed) {
        return Ok(parsed);
    }

    PasswordHash::new(trimmed).map_err(|error| format!("invalid admin password hash: {error}"))?;
    let mut accounts = HashMap::new();
    accounts.insert(
        ADMIN_ACCOUNT.to_owned(),
        Account {
            password_hash: trimmed.to_owned(),
            totp: None,
            updated_at_ms: 0,
        },
    );
    Ok(AccountFile { accounts })
}

/// Writes the admin account back to `path` in the current JSON format.
/// Shared by the running server (password change, TOTP changes) and the
/// `reset-password` / `disable-totp` CLI subcommands, which call it directly
/// without going through [`AuthManager`].
pub async fn write_account(path: &Path, account: &Account) -> Result<(), String> {
    let mut accounts = HashMap::new();
    accounts.insert(ADMIN_ACCOUNT.to_owned(), account.clone());
    let file = AccountFile { accounts };
    let serialized = serde_json::to_vec_pretty(&file)
        .map_err(|error| format!("failed to encode account file: {error}"))?;
    atomic_write_secure(path, &serialized).await
}

/// Reads the single admin account out of `path`. Shared by the CLI recovery
/// commands, which — unlike the running server — have no in-memory
/// [`AuthManager`] to read from and always go straight to disk.
pub fn load_admin_account(path: &Path) -> Result<Account, String> {
    let account_file = load_account_file(path)?;
    account_file
        .accounts
        .get(ADMIN_ACCOUNT)
        .cloned()
        .ok_or_else(|| format!("{} does not contain an admin account", path.display()))
}

/// `reset-password` CLI service: overwrites only `password_hash`, leaving
/// TOTP untouched. See [`disable_totp_cli`] for the separate TOTP recovery
/// path.
pub async fn reset_password_cli(path: &Path, new_password: &str) -> Result<(), String> {
    validate_new_password(new_password)?;
    let mut account = load_admin_account(path)?;
    account.password_hash = hash_password(new_password)?;
    account.updated_at_ms = now_ms();
    write_account(path, &account).await
}

/// `disable-totp` CLI service: clears TOTP and its recovery codes. The
/// caller is responsible for checking whether TOTP is enabled and for any
/// interactive confirmation before calling this.
pub async fn disable_totp_cli(path: &Path) -> Result<(), String> {
    let mut account = load_admin_account(path)?;
    account.totp = None;
    account.updated_at_ms = now_ms();
    write_account(path, &account).await
}

pub fn now_ms() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |duration| {
            u64::try_from(duration.as_millis()).unwrap_or(u64::MAX)
        })
}

async fn is_rate_limited(
    failures: &Mutex<HashMap<IpAddr, FailedLogins>>,
    source_ip: IpAddr,
) -> bool {
    let now = Instant::now();
    let mut failures = failures.lock().await;
    failures.retain(|_, entry| now.duration_since(entry.started_at) < FAILURE_WINDOW);
    failures
        .get(&source_ip)
        .is_some_and(|entry| entry.count >= MAX_FAILURES)
}

async fn record_failure(failures: &Mutex<HashMap<IpAddr, FailedLogins>>, source_ip: IpAddr) {
    let now = Instant::now();
    let mut failures = failures.lock().await;
    let entry = failures.entry(source_ip).or_insert(FailedLogins {
        count: 0,
        started_at: now,
    });
    if now.duration_since(entry.started_at) >= FAILURE_WINDOW {
        entry.count = 0;
        entry.started_at = now;
    }
    entry.count = entry.count.saturating_add(1);
    drop(failures);
}

async fn verify_password(password_hash: String, password: String) -> bool {
    tokio::task::spawn_blocking(move || {
        let Ok(parsed_hash) = PasswordHash::new(&password_hash) else {
            return false;
        };
        Argon2::default()
            .verify_password(password.as_bytes(), &parsed_hash)
            .is_ok()
    })
    .await
    .unwrap_or(false)
}

pub fn hash_password(password: &str) -> Result<String, String> {
    if password.is_empty() || password.len() > MAX_PASSWORD_BYTES {
        return Err("password must contain between 1 and 1024 bytes".to_owned());
    }
    let salt = SaltString::encode_b64(&rand::random::<[u8; 16]>())
        .map_err(|error| format!("failed to create password salt: {error}"))?;
    Argon2::default()
        .hash_password(password.as_bytes(), &salt)
        .map(|hash| hash.to_string())
        .map_err(|error| format!("failed to hash password: {error}"))
}

/// Shared by the web password-change endpoint and the `reset-password` CLI
/// command so both enforce the same strength floor.
pub fn validate_new_password(password: &str) -> Result<(), String> {
    if password.len() < MIN_PASSWORD_BYTES || password.len() > MAX_PASSWORD_BYTES {
        return Err(format!(
            "password must contain between {MIN_PASSWORD_BYTES} and {MAX_PASSWORD_BYTES} bytes"
        ));
    }
    Ok(())
}

pub async fn login(
    State(auth): State<AuthManager>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    axum::Extension(request_id): axum::Extension<RequestId>,
    headers: HeaderMap,
    Json(payload): Json<LoginRequest>,
) -> Response {
    if !same_origin(&headers) {
        warn!(
            event = "auth_login",
            request_id = %request_id.0,
            source_ip = %peer.ip(),
            result = "rejected",
            reason = "origin",
            "login rejected"
        );
        return error_response(
            StatusCode::FORBIDDEN,
            "forbidden",
            "request origin is not allowed",
        );
    }

    match auth.login(peer.ip(), payload.password).await {
        LoginResult::Authenticated(token) => {
            auth.audit()
                .log_admin(
                    &request_id,
                    peer.ip(),
                    "auth_login",
                    "success",
                    None,
                    "administrator logged in",
                )
                .await;
            let mut response = Json(AuthStatus::authenticated()).into_response();
            if let Ok(value) = HeaderValue::from_str(&auth.session_cookie(&token)) {
                response.headers_mut().insert(SET_COOKIE, value);
            }
            response
        }
        LoginResult::TotpRequired(preauth_token) => {
            auth.audit()
                .log_admin(
                    &request_id,
                    peer.ip(),
                    "auth_login",
                    "totp_required",
                    None,
                    "administrator password confirmed; two-factor code required",
                )
                .await;
            let mut response = Json(AuthStatus::totp_required()).into_response();
            if let Ok(value) = HeaderValue::from_str(&auth.preauth_cookie(&preauth_token)) {
                response.headers_mut().insert(SET_COOKIE, value);
            }
            response
        }
        LoginResult::Invalid => {
            auth.audit()
                .log_admin(
                    &request_id,
                    peer.ip(),
                    "auth_login",
                    "failure",
                    None,
                    "administrator login failed",
                )
                .await;
            error_response(
                StatusCode::UNAUTHORIZED,
                "invalid_credentials",
                "password is incorrect",
            )
        }
        LoginResult::RateLimited => {
            auth.audit()
                .log_admin(
                    &request_id,
                    peer.ip(),
                    "auth_login",
                    "rate_limited",
                    None,
                    "administrator login rate limited",
                )
                .await;
            error_response(
                StatusCode::TOO_MANY_REQUESTS,
                "rate_limited",
                "too many login attempts; try again later",
            )
        }
    }
}

pub async fn login_totp(
    State(auth): State<AuthManager>,
    ConnectInfo(peer): ConnectInfo<SocketAddr>,
    axum::Extension(request_id): axum::Extension<RequestId>,
    headers: HeaderMap,
    Json(payload): Json<LoginTotpRequest>,
) -> Response {
    if !same_origin(&headers) {
        warn!(
            event = "auth_login_totp",
            request_id = %request_id.0,
            source_ip = %peer.ip(),
            result = "rejected",
            reason = "origin",
            "two-factor login rejected"
        );
        return error_response(
            StatusCode::FORBIDDEN,
            "forbidden",
            "request origin is not allowed",
        );
    }

    match auth.login_totp(peer.ip(), &headers, payload.code).await {
        LoginTotpResult::Authenticated(token) => {
            auth.audit()
                .log_admin(
                    &request_id,
                    peer.ip(),
                    "auth_login_totp",
                    "success",
                    None,
                    "administrator completed two-factor login",
                )
                .await;
            let mut response = Json(AuthStatus::authenticated()).into_response();
            if let Ok(value) = HeaderValue::from_str(&auth.session_cookie(&token)) {
                response.headers_mut().append(SET_COOKIE, value);
            }
            if let Ok(value) = HeaderValue::from_str(&auth.expired_preauth_cookie()) {
                response.headers_mut().append(SET_COOKIE, value);
            }
            response
        }
        LoginTotpResult::Invalid => {
            auth.audit()
                .log_admin(
                    &request_id,
                    peer.ip(),
                    "auth_login_totp",
                    "failure",
                    None,
                    "two-factor code was incorrect",
                )
                .await;
            error_response(
                StatusCode::UNAUTHORIZED,
                "invalid_totp_code",
                "the code is incorrect",
            )
        }
        LoginTotpResult::RateLimited => {
            auth.audit()
                .log_admin(
                    &request_id,
                    peer.ip(),
                    "auth_login_totp",
                    "rate_limited",
                    None,
                    "two-factor login rate limited",
                )
                .await;
            error_response(
                StatusCode::TOO_MANY_REQUESTS,
                "rate_limited",
                "too many attempts; try again later",
            )
        }
        LoginTotpResult::NoPendingLogin => error_response(
            StatusCode::UNAUTHORIZED,
            "totp_session_expired",
            "sign in again with your password",
        ),
    }
}

pub async fn status(State(auth): State<AuthManager>, headers: HeaderMap) -> Json<AuthStatus> {
    if auth.is_authenticated(&headers).await {
        Json(AuthStatus::authenticated())
    } else {
        Json(AuthStatus::unauthenticated())
    }
}

pub async fn logout(
    State(auth): State<AuthManager>,
    axum::Extension(request_id): axum::Extension<RequestId>,
    axum::Extension(user): axum::Extension<AuthenticatedUser>,
    headers: HeaderMap,
) -> Response {
    auth.logout(&headers).await;
    auth.audit()
        .log_admin(
            &request_id,
            user.source_ip,
            "auth_logout",
            "success",
            None,
            "administrator logged out",
        )
        .await;
    signed_out_response(&auth)
}

/// Builds an `authenticated: false` response with the session cookie
/// expired. Shared by [`logout`] and the successful branch of
/// [`change_password`], which also ends the caller's session.
fn signed_out_response(auth: &AuthManager) -> Response {
    let mut response = Json(AuthStatus::unauthenticated()).into_response();
    if let Ok(value) = HeaderValue::from_str(&auth.expired_cookie()) {
        response.headers_mut().insert(SET_COOKIE, value);
    }
    response
}

pub async fn change_password(
    State(auth): State<AuthManager>,
    axum::Extension(request_id): axum::Extension<RequestId>,
    axum::Extension(user): axum::Extension<AuthenticatedUser>,
    Json(payload): Json<ChangePasswordRequest>,
) -> Response {
    match auth
        .change_password(
            user.source_ip,
            payload.current_password,
            payload.new_password,
        )
        .await
    {
        ChangePasswordResult::Changed => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "password_change",
                    "success",
                    None,
                    "administrator password changed",
                )
                .await;
            signed_out_response(&auth)
        }
        ChangePasswordResult::InvalidCurrentPassword => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "password_change",
                    "failure",
                    Some("invalid_current_password".to_owned()),
                    "administrator password confirmation failed",
                )
                .await;
            error_response(
                StatusCode::UNAUTHORIZED,
                "invalid_current_password",
                "current password is incorrect",
            )
        }
        ChangePasswordResult::RateLimited => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "password_change",
                    "rate_limited",
                    None,
                    "administrator password confirmation rate limited",
                )
                .await;
            error_response(
                StatusCode::TOO_MANY_REQUESTS,
                "rate_limited",
                "too many password confirmation attempts; try again later",
            )
        }
        ChangePasswordResult::InvalidNewPassword => error_response(
            StatusCode::BAD_REQUEST,
            "invalid_new_password",
            "new password must contain between 12 and 1024 bytes",
        ),
        ChangePasswordResult::NotPersistent => error_response(
            StatusCode::CONFLICT,
            "password_change_unavailable",
            "password cannot be changed while DECKOX_ADMIN_PASSWORD_HASH is configured",
        ),
        ChangePasswordResult::Failed(error) => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "password_change",
                    "failure",
                    Some(error),
                    "administrator password change failed",
                )
                .await;
            error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                "password_change_failed",
                "failed to save the new password",
            )
        }
    }
}

pub async fn totp_status(State(auth): State<AuthManager>) -> Json<TotpStatusResponse> {
    Json(auth.totp_status().await)
}

pub async fn totp_setup(
    State(auth): State<AuthManager>,
    axum::Extension(request_id): axum::Extension<RequestId>,
    axum::Extension(user): axum::Extension<AuthenticatedUser>,
    headers: HeaderMap,
) -> Response {
    let Some(token) = session_token(&headers) else {
        return error_response(
            StatusCode::UNAUTHORIZED,
            "authentication_required",
            "authentication is required",
        );
    };
    match auth.totp_setup(&token).await {
        TotpSetupResult::Ready {
            secret_base32,
            otpauth_uri,
        } => Json(TotpSetupResponse {
            secret_base32,
            otpauth_uri,
        })
        .into_response(),
        TotpSetupResult::NotPersistent => error_response(
            StatusCode::CONFLICT,
            "totp_unavailable",
            "two-factor authentication cannot be changed while DECKOX_ADMIN_PASSWORD_HASH is configured",
        ),
        TotpSetupResult::Failed(error) => {
            warn!(
                event = "totp_setup",
                request_id = %request_id.0,
                actor = "admin",
                source_ip = %user.source_ip,
                result = "failure",
                reason = %error,
                "TOTP setup failed"
            );
            error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                "totp_setup_failed",
                "failed to start two-factor setup",
            )
        }
    }
}

pub async fn totp_confirm(
    State(auth): State<AuthManager>,
    axum::Extension(request_id): axum::Extension<RequestId>,
    axum::Extension(user): axum::Extension<AuthenticatedUser>,
    headers: HeaderMap,
    Json(payload): Json<TotpConfirmRequest>,
) -> Response {
    let Some(token) = session_token(&headers) else {
        return error_response(
            StatusCode::UNAUTHORIZED,
            "authentication_required",
            "authentication is required",
        );
    };
    match auth.totp_confirm(&token, payload.code).await {
        TotpConfirmResult::Confirmed(recovery_codes) => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "totp_enabled",
                    "success",
                    None,
                    "two-factor authentication enabled",
                )
                .await;
            Json(TotpConfirmResponse { recovery_codes }).into_response()
        }
        TotpConfirmResult::InvalidCode => error_response(
            StatusCode::UNAUTHORIZED,
            "invalid_totp_code",
            "the code is incorrect",
        ),
        TotpConfirmResult::NoPendingSetup => error_response(
            StatusCode::CONFLICT,
            "totp_setup_expired",
            "start two-factor setup again",
        ),
        TotpConfirmResult::NotPersistent => error_response(
            StatusCode::CONFLICT,
            "totp_unavailable",
            "two-factor authentication cannot be changed while DECKOX_ADMIN_PASSWORD_HASH is configured",
        ),
        TotpConfirmResult::Failed(error) => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "totp_enabled",
                    "failure",
                    Some(error),
                    "failed to enable two-factor authentication",
                )
                .await;
            error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                "totp_confirm_failed",
                "failed to enable two-factor authentication",
            )
        }
    }
}

pub async fn totp_disable(
    State(auth): State<AuthManager>,
    axum::Extension(request_id): axum::Extension<RequestId>,
    axum::Extension(user): axum::Extension<AuthenticatedUser>,
    Json(payload): Json<TotpDisableRequest>,
) -> Response {
    match auth
        .totp_disable(user.source_ip, payload.current_password, payload.code)
        .await
    {
        TotpDisableResult::Disabled => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "totp_disabled",
                    "success",
                    None,
                    "two-factor authentication disabled",
                )
                .await;
            Json(TotpStatusResponse {
                enabled: false,
                recovery_codes_remaining: 0,
            })
            .into_response()
        }
        TotpDisableResult::NotEnabled => error_response(
            StatusCode::CONFLICT,
            "totp_not_enabled",
            "two-factor authentication is not enabled",
        ),
        TotpDisableResult::InvalidCurrentPassword => {
            totp_invalid_current_password_response(&auth, &request_id, &user).await
        }
        TotpDisableResult::InvalidCode => error_response(
            StatusCode::UNAUTHORIZED,
            "invalid_totp_code",
            "the code is incorrect",
        ),
        TotpDisableResult::RateLimited => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "totp_disabled",
                    "rate_limited",
                    None,
                    "two-factor disable confirmation rate limited",
                )
                .await;
            error_response(
                StatusCode::TOO_MANY_REQUESTS,
                "rate_limited",
                "too many attempts; try again later",
            )
        }
        TotpDisableResult::NotPersistent => error_response(
            StatusCode::CONFLICT,
            "totp_unavailable",
            "two-factor authentication cannot be changed while DECKOX_ADMIN_PASSWORD_HASH is configured",
        ),
        TotpDisableResult::Failed(error) => {
            auth.audit()
                .log_admin(
                    &request_id,
                    user.source_ip,
                    "totp_disabled",
                    "failure",
                    Some(error),
                    "failed to disable two-factor authentication",
                )
                .await;
            error_response(
                StatusCode::INTERNAL_SERVER_ERROR,
                "totp_disable_failed",
                "failed to disable two-factor authentication",
            )
        }
    }
}

async fn totp_invalid_current_password_response(
    auth: &AuthManager,
    request_id: &RequestId,
    user: &AuthenticatedUser,
) -> Response {
    auth.audit()
        .log_admin(
            request_id,
            user.source_ip,
            "totp_disabled",
            "failure",
            Some("invalid_current_password".to_owned()),
            "two-factor disable confirmation failed",
        )
        .await;
    error_response(
        StatusCode::UNAUTHORIZED,
        "invalid_current_password",
        "current password is incorrect",
    )
}

pub async fn require_auth(
    State(auth): State<AuthManager>,
    mut request: Request,
    next: Next,
) -> Response {
    let source_ip = request
        .extensions()
        .get::<ConnectInfo<SocketAddr>>()
        .map_or_else(|| IpAddr::from([0, 0, 0, 0]), |peer| peer.ip());
    let request_id = request
        .extensions()
        .get::<RequestId>()
        .map_or("unknown", |value| value.0.as_str());

    if !auth.is_authenticated(request.headers()).await {
        warn!(
            event = "auth_required",
            request_id,
            source_ip = %source_ip,
            result = "rejected",
            "unauthenticated API request rejected"
        );
        return error_response(
            StatusCode::UNAUTHORIZED,
            "authentication_required",
            "authentication is required",
        );
    }
    if requires_same_origin(request.method(), request.headers()) && !same_origin(request.headers())
    {
        warn!(
            event = "auth_origin",
            request_id,
            actor = "admin",
            source_ip = %source_ip,
            result = "rejected",
            "cross-origin API request rejected"
        );
        return error_response(
            StatusCode::FORBIDDEN,
            "forbidden",
            "request origin is not allowed",
        );
    }

    request
        .extensions_mut()
        .insert(AuthenticatedUser { source_ip });
    next.run(request).await
}

fn session_token(headers: &HeaderMap) -> Option<String> {
    cookie_value(headers, SESSION_COOKIE)
}

fn preauth_token(headers: &HeaderMap) -> Option<String> {
    cookie_value(headers, PREAUTH_COOKIE)
}

fn cookie_value(headers: &HeaderMap, name: &str) -> Option<String> {
    headers
        .get(COOKIE)?
        .to_str()
        .ok()?
        .split(';')
        .find_map(|cookie| {
            let (cookie_name, value) = cookie.trim().split_once('=')?;
            (cookie_name == name && !value.is_empty()).then(|| value.to_owned())
        })
}

fn same_origin(headers: &HeaderMap) -> bool {
    let Some(host) = headers.get(HOST).and_then(|value| value.to_str().ok()) else {
        return false;
    };
    let Some(origin) = headers.get(ORIGIN).and_then(|value| value.to_str().ok()) else {
        return false;
    };
    origin == format!("http://{host}") || origin == format!("https://{host}")
}

const fn is_state_changing(method: &Method) -> bool {
    !matches!(*method, Method::GET | Method::HEAD | Method::OPTIONS)
}

fn requires_same_origin(method: &Method, headers: &HeaderMap) -> bool {
    is_state_changing(method)
        || headers
            .get(UPGRADE)
            .is_some_and(|value| value.as_bytes().eq_ignore_ascii_case(b"websocket"))
}

#[cfg(test)]
mod tests {
    use std::{collections::HashMap, net::IpAddr, sync::Arc};

    use axum::http::{HeaderMap, HeaderValue, Method, header};
    use tokio::sync::{Mutex, RwLock};

    use super::{
        Account, AuditLog, AuthInner, AuthManager, MAX_FAILURES, PasswordConfirmationResult,
        TotpSecret, disable_totp_cli, hash_password, is_rate_limited, load_account_file,
        load_admin_account, record_failure, requires_same_origin, reset_password_cli, same_origin,
        session_token, write_account,
    };

    fn test_auth(password: &str) -> AuthManager {
        test_auth_with_path(password, None)
    }

    /// An `account_path` of `Some` is required for TOTP setup/confirm/login,
    /// which refuse to run in the non-persistent `DECKOX_ADMIN_PASSWORD_HASH`
    /// mode that a `None` path represents.
    fn test_auth_with_path(
        password: &str,
        account_path: Option<std::path::PathBuf>,
    ) -> AuthManager {
        AuthManager {
            inner: Arc::new(AuthInner {
                account: RwLock::new(Account {
                    password_hash: hash_password(password).expect("password should hash"),
                    totp: None,
                    updated_at_ms: 0,
                }),
                account_path,
                secure_cookie: false,
                sessions: Mutex::new(HashMap::new()),
                failures: Mutex::new(HashMap::new()),
                password_change_failures: Mutex::new(HashMap::new()),
                totp_login_failures: Mutex::new(HashMap::new()),
                account_write: Mutex::new(()),
                audit: AuditLog::new(std::env::temp_dir().join(format!(
                    "deckox-auth-test-{}.log",
                    hex::encode(rand::random::<[u8; 8]>())
                ))),
                pending_logins: Mutex::new(HashMap::new()),
                pending_totp_setup: Mutex::new(HashMap::new()),
            }),
        }
    }

    #[test]
    fn hashes_password_with_argon2id() {
        let hash = hash_password("test-password").expect("password should hash");
        assert!(hash.starts_with("$argon2id$"));
    }

    #[test]
    fn extracts_session_cookie() {
        let mut headers = HeaderMap::new();
        headers.insert(
            header::COOKIE,
            HeaderValue::from_static("theme=light; deckox_session=abc123"),
        );
        assert_eq!(session_token(&headers).as_deref(), Some("abc123"));
    }

    #[test]
    fn validates_same_origin() {
        let mut headers = HeaderMap::new();
        headers.insert(header::HOST, HeaderValue::from_static("192.168.1.21:8080"));
        headers.insert(
            header::ORIGIN,
            HeaderValue::from_static("http://192.168.1.21:8080"),
        );
        assert!(same_origin(&headers));
    }

    #[test]
    fn websocket_upgrade_requires_same_origin() {
        let mut headers = HeaderMap::new();
        headers.insert(header::UPGRADE, HeaderValue::from_static("websocket"));

        assert!(requires_same_origin(&Method::GET, &headers));
        assert!(!requires_same_origin(&Method::GET, &HeaderMap::new()));
    }

    #[tokio::test]
    async fn rate_limits_password_confirmation_failures() {
        let failures = Mutex::new(HashMap::new());
        let source_ip = IpAddr::from([192, 0, 2, 1]);
        for _ in 0..MAX_FAILURES {
            record_failure(&failures, source_ip).await;
        }
        assert!(is_rate_limited(&failures, source_ip).await);
    }

    #[tokio::test]
    async fn confirms_current_password_and_clears_failures() {
        let auth = test_auth("correct-test-password");
        let source_ip = IpAddr::from([192, 0, 2, 2]);

        assert!(matches!(
            auth.confirm_current_password(source_ip, "wrong-password".to_owned())
                .await,
            PasswordConfirmationResult::Invalid
        ));
        assert!(matches!(
            auth.confirm_current_password(source_ip, "correct-test-password".to_owned())
                .await,
            PasswordConfirmationResult::Confirmed
        ));
        assert!(
            !is_rate_limited(&auth.inner.password_change_failures, source_ip).await,
            "successful confirmation should clear failures"
        );
    }

    #[test]
    fn upgrades_legacy_bare_hash_file_on_read() {
        let path = std::env::temp_dir().join(format!(
            "deckox-account-legacy-{}.hash",
            hex::encode(rand::random::<[u8; 8]>())
        ));
        let hash = hash_password("legacy-password").expect("password should hash");
        std::fs::write(&path, format!("{hash}\n")).expect("legacy hash should write");

        let account_file = load_account_file(&path).expect("legacy hash should parse");
        let account = account_file
            .accounts
            .get(super::ADMIN_ACCOUNT)
            .expect("admin account should exist");
        assert_eq!(account.password_hash, hash);
        assert!(account.totp.is_none());

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn reads_current_json_account_format() {
        let path = std::env::temp_dir().join(format!(
            "deckox-account-json-{}.json",
            hex::encode(rand::random::<[u8; 8]>())
        ));
        let hash = hash_password("json-password").expect("password should hash");
        std::fs::write(
            &path,
            format!(
                r#"{{"accounts":{{"admin":{{"password_hash":"{hash}","totp":null,"updated_at_ms":123}}}}}}"#
            ),
        )
        .expect("account file should write");

        let account_file = load_account_file(&path).expect("account file should parse");
        let account = account_file
            .accounts
            .get(super::ADMIN_ACCOUNT)
            .expect("admin account should exist");
        assert_eq!(account.password_hash, hash);
        assert_eq!(account.updated_at_ms, 123);

        let _ = std::fs::remove_file(&path);
    }

    #[tokio::test]
    async fn reset_password_cli_updates_only_the_password_hash() {
        let path = std::env::temp_dir().join(format!(
            "deckox-account-reset-cli-{}.json",
            hex::encode(rand::random::<[u8; 8]>())
        ));
        let account = Account {
            password_hash: hash_password("old-password").expect("password should hash"),
            totp: Some(TotpSecret {
                secret_base32: "JBSWY3DPEHPK3PXP".to_owned(),
                recovery_code_hashes: vec![
                    hash_password("ABCDE-12345").expect("recovery code should hash"),
                ],
                last_used_step: None,
            }),
            updated_at_ms: 0,
        };
        write_account(&path, &account)
            .await
            .expect("account should write");

        reset_password_cli(&path, "brand-new-password")
            .await
            .expect("reset should succeed");

        let reloaded = load_admin_account(&path).expect("account should reload");
        assert_ne!(reloaded.password_hash, account.password_hash);
        assert!(
            reloaded.totp.is_some(),
            "reset-password must leave TOTP untouched"
        );

        let _ = std::fs::remove_file(&path);
    }

    #[tokio::test]
    async fn disable_totp_cli_clears_totp_and_recovery_codes() {
        let path = std::env::temp_dir().join(format!(
            "deckox-account-disable-totp-cli-{}.json",
            hex::encode(rand::random::<[u8; 8]>())
        ));
        let account = Account {
            password_hash: hash_password("some-password").expect("password should hash"),
            totp: Some(TotpSecret {
                secret_base32: "JBSWY3DPEHPK3PXP".to_owned(),
                recovery_code_hashes: vec![
                    hash_password("ABCDE-12345").expect("recovery code should hash"),
                ],
                last_used_step: None,
            }),
            updated_at_ms: 0,
        };
        write_account(&path, &account)
            .await
            .expect("account should write");

        disable_totp_cli(&path)
            .await
            .expect("disable should succeed");

        let reloaded = load_admin_account(&path).expect("account should reload");
        assert!(reloaded.totp.is_none());
        assert_eq!(
            reloaded.password_hash, account.password_hash,
            "disable-totp must leave the password untouched"
        );

        let _ = std::fs::remove_file(&path);
    }

    #[tokio::test]
    async fn recovery_code_is_consumed_after_use() {
        let mut account = Account {
            password_hash: hash_password("pw-for-recovery-test").expect("password should hash"),
            totp: Some(super::TotpSecret {
                secret_base32: "JBSWY3DPEHPK3PXP".to_owned(),
                recovery_code_hashes: vec![
                    hash_password("ABCDE-12345").expect("recovery code should hash"),
                ],
                last_used_step: None,
            }),
            updated_at_ms: 0,
        };

        assert!(super::verify_totp_or_recovery_code(&mut account, "ABCDE-12345").await);
        assert!(
            account
                .totp
                .as_ref()
                .unwrap()
                .recovery_code_hashes
                .is_empty(),
            "a used recovery code must be removed"
        );
        assert!(
            !super::verify_totp_or_recovery_code(&mut account, "ABCDE-12345").await,
            "a consumed recovery code must not verify again"
        );
    }

    #[tokio::test]
    async fn totp_setup_confirm_and_login_round_trip() {
        let path = std::env::temp_dir().join(format!(
            "deckox-totp-test-{}.json",
            hex::encode(rand::random::<[u8; 8]>())
        ));
        let auth = test_auth_with_path("totp-round-trip-password", Some(path.clone()));
        let session_token = "test-session-token";

        let super::TotpSetupResult::Ready { secret_base32, .. } =
            auth.totp_setup(session_token).await
        else {
            panic!("setup should succeed for a persistent account");
        };
        let code = super::build_totp(&secret_base32)
            .expect("stored secret should build a TOTP")
            .generate_current()
            .expect("a code should generate for the current time");

        let super::TotpConfirmResult::Confirmed(recovery_codes) =
            auth.totp_confirm(session_token, code.clone()).await
        else {
            panic!("confirm should succeed with a valid code");
        };
        assert_eq!(recovery_codes.len(), super::RECOVERY_CODE_COUNT);

        let source_ip = IpAddr::from([192, 0, 2, 10]);
        let super::LoginResult::TotpRequired(preauth_token) = auth
            .login(source_ip, "totp-round-trip-password".to_owned())
            .await
        else {
            panic!("login should require a TOTP code once enabled");
        };

        let mut headers = HeaderMap::new();
        headers.insert(
            header::COOKIE,
            HeaderValue::from_str(&format!("deckox_preauth={preauth_token}"))
                .expect("cookie header should build"),
        );
        assert!(
            !matches!(
                auth.login_totp(source_ip, &headers, code).await,
                super::LoginTotpResult::Authenticated(_)
            ),
            "the code already accepted by confirm must not be replayable for login"
        );

        let super::LoginResult::TotpRequired(preauth_token) = auth
            .login(source_ip, "totp-round-trip-password".to_owned())
            .await
        else {
            panic!("login should still require a TOTP code after the failed replay");
        };
        headers.insert(
            header::COOKIE,
            HeaderValue::from_str(&format!("deckox_preauth={preauth_token}"))
                .expect("cookie header should build"),
        );
        assert!(
            matches!(
                auth.login_totp(source_ip, &headers, recovery_codes[0].clone())
                    .await,
                super::LoginTotpResult::Authenticated(_)
            ),
            "a fresh recovery code should still authenticate"
        );

        let _ = std::fs::remove_file(&path);
    }
}
