import type { WebModule } from "../../widgets/types";

/** Host information and live resource use, from the Agent's `system` module. */
const system: WebModule = {
  id: "system",
  order: 10,
  titleKey: "widgets.system.title",
  widgets: [
    {
      id: "system.summary",
      titleKey: "widgets.system.summary.title",
      descriptionKey: "widgets.system.summary.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/SummaryWidget.vue"),
      size: { default: { w: 4, h: 2 }, min: { w: 3, h: 2 } },
    },
    {
      id: "system.live",
      titleKey: "widgets.system.live.title",
      descriptionKey: "widgets.system.live.description",
      requires: ["realtime", "system"],
      chrome: "bare",
      component: () => import("./widgets/LiveWidget.vue"),
      size: { default: { w: 4, h: 2 }, min: { w: 3, h: 2 } },
    },
    {
      id: "system.cpu",
      titleKey: "widgets.system.cpu.title",
      descriptionKey: "widgets.system.cpu.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/CpuWidget.vue"),
      size: { default: { w: 4, h: 3 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.memory",
      titleKey: "widgets.system.memory.title",
      descriptionKey: "widgets.system.memory.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/MemoryWidget.vue"),
      size: { default: { w: 4, h: 3 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.load",
      titleKey: "widgets.system.load.title",
      descriptionKey: "widgets.system.load.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/LoadWidget.vue"),
      size: { default: { w: 4, h: 3 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.swap",
      titleKey: "widgets.system.swap.title",
      descriptionKey: "widgets.system.swap.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/SwapWidget.vue"),
      size: { default: { w: 4, h: 3 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.network",
      titleKey: "widgets.system.network.title",
      descriptionKey: "widgets.system.network.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/NetworkWidget.vue"),
      size: { default: { w: 4, h: 3 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.disk-io",
      titleKey: "widgets.system.diskIo.title",
      descriptionKey: "widgets.system.diskIo.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/DiskIoWidget.vue"),
      size: { default: { w: 4, h: 3 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.temperature",
      titleKey: "widgets.system.temperature.title",
      descriptionKey: "widgets.system.temperature.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/TemperatureWidget.vue"),
      size: { default: { w: 4, h: 3 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.uptime",
      titleKey: "widgets.system.uptime.title",
      descriptionKey: "widgets.system.uptime.description",
      requires: ["system"],
      chrome: "bare",
      component: () => import("./widgets/UptimeWidget.vue"),
      size: { default: { w: 4, h: 2 }, min: { w: 2, h: 2 } },
    },
    {
      id: "system.info",
      titleKey: "widgets.system.info.title",
      descriptionKey: "widgets.system.info.description",
      requires: ["system"],
      chrome: "frame",
      component: () => import("./widgets/InfoWidget.vue"),
      size: { default: { w: 12, h: "auto" }, min: { w: 4, h: 2 } },
    },
  ],
  messages: {
    ja: {
      widgets: {
        system: {
          title: "システム",
          summary: { title: "ホストの概要", description: "ホスト名、OS、稼働時間、アーキテクチャを表示します。" },
          live: { title: "リアルタイム接続", description: "リアルタイム更新の接続状態と、最後に更新した時刻を表示します。" },
          cpu: { title: "CPU", description: "CPUの使用率を、数値と推移のグラフで表示します。" },
          memory: { title: "メモリ", description: "メモリの使用量と使用率を表示します。" },
          load: { title: "負荷", description: "1分・5分・15分の負荷平均を表示します。" },
          swap: { title: "スワップ", description: "スワップの使用率を表示します。" },
          network: { title: "ネットワーク", description: "ネットワークの受信・送信の速度を表示します。" },
          diskIo: { title: "ディスクI/O", description: "ディスクの読み込み・書き込みの速度を表示します。" },
          temperature: { title: "CPU温度", description: "CPU温度を表示します。センサーがあるホストで使えます。" },
          uptime: { title: "稼働時間", description: "ホストが起動してからの経過時間を表示します。" },
          info: { title: "システム情報", description: "ホスト名、OS、カーネル、タイムゾーン、アクセスURLを一覧で表示します。" },
        },
      },
    },
    en: {
      widgets: {
        system: {
          title: "System",
          summary: { title: "Host summary", description: "Host name, OS, uptime and architecture." },
          live: { title: "Live connection", description: "State of the live updates and the time of the last one." },
          cpu: { title: "CPU", description: "CPU usage as a number and a chart over time." },
          memory: { title: "Memory", description: "Memory in use and its percentage." },
          load: { title: "Load average", description: "Load average over 1, 5 and 15 minutes." },
          swap: { title: "Swap", description: "Swap usage." },
          network: { title: "Network", description: "Network receive and transmit rate." },
          diskIo: { title: "Disk I/O", description: "Disk read and write rate." },
          temperature: { title: "CPU temperature", description: "CPU temperature, on hosts with a sensor." },
          uptime: { title: "Uptime", description: "How long the host has been running." },
          info: { title: "System information", description: "Host name, OS, kernel, time zone and access URLs as a list." },
        },
      },
    },
  },
};

export default system;
